name: Basic github action test

on: [push]

jobs:
  simpeHelloWorldJob:
    runs-on: ubuntu-20.04

    env:
      TEST_SECRET: ${{ secrets.test }}
      EVENT: ${{github.event.pusher.name}}
    steps:
      - uses: actions/checkout@v3
      - name: "preload config"
        run: | 
          echo 'starting' \ &&
          echo 'your secret: '$EVENT
