name: PR_GATE
on: 
  - pull_request
  - workflow_dispatch
jobs:
  PR_validation:
    runs-on: ubuntu-20.04
    env:
      ALLOWED_PUSHERS: ${{ secrets.ALLOWED_PUSHERS}}
      BRANCH: ${{ github.ref_name}}
      PUSHER: ${{ github.event.pull_request.user.login }}
    
    steps:
      - uses: actions/checkout@v3
      - name: env setup
        run: |
          pip install -r deps/test-req.txt
      - name: event
        run: |
          echo $EVENT
      - name: Run Test
        run: |
          python -m pytest -k validate_pusher -v
